[package]
name = "lense"
description = "High performance by-ref, transmute backed reader."
license = "MIT"
version = "0.1.0"
authors = ["James McGlashan <github@darkfox.id.au>"]

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
